### ISSUE TITLE
Beat Saber version compatibility

### ISSUE THREAD

**Issue by mariobrostech** [SamuelTulach/OcuFix#1]
Hi,

I am interested in running Beat Saber v1.18.3 since it is the last version that's compatible with BeatTogether for online multiplayer using custom songs. Which versions of OcuFix are compatible with this older version of the game? Would the versions built for v1.18.1 work?

Thanks in advance!

**Comment by SamuelTulach** [comment]
The beauty of GitHub notifications is that it just never gets to me (apart from stupid Feature Previews) so sorry for late response.

Using any BS version with the latest build should be fine. It does not depend on the game at all apart from BSIPA and BSML, so as long as you have a working mod injector and a working BSML library then it should work on that BS version - in other words it should be backwards compatible with most BS versions.

**Comment by mariobrostech** [comment]
Awesome, thanks! If you could add that to the README as well, I'd really appreciate it. I'm sure that others have asked themselves similar questions before, and having it there would go a long way towards preventing confusion.

**Comment by ghost** [comment]
I need to test it with v1.20 its backwards compatible.. what does  
"dependsOn": {
    "BSIPA": "^4.2.1",

mean i mean the ^  does it mean BSIPA 4.2.1 or higher? or lower?

**Comment by SamuelTulach** [comment]
> I need to test it with v1.20 its backwards compatible.. what does "dependsOn": { "BSIPA": "^4.2.1",
> 
> mean i mean the ^ does it mean BSIPA 4.2.1 or higher? or lower?

It means higher (putting in lower would not really be that logical would it?), but I basically just used the latest version at the time when I started working on the mod so it will probably work just fine on older versions.
